INSERT INTO tb_party_hall (NAME, CAPACITY, VALUE_PER_GUEST) VALUES ('Itamaraty Hall', 230, 100.0);
INSERT INTO tb_party_hall (NAME, CAPACITY, VALUE_PER_GUEST) VALUES ('Le Buffet', 180, 130.0);
INSERT INTO tb_party_hall (NAME, CAPACITY, VALUE_PER_GUEST) VALUES ('Choupana do guadala', 120, 35.0);